In [7]:
import numpy as np
import time

In [8]:
arr = np.array([1,2,3,4,5])
print(arr)

arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [9]:
py_list = [1, 2, 3]
print("Python list multiplication", py_list * 2)

np_array = np.array([1, 2, 3])
print("Numpy array multiplication", np_array * 2)

Python list multiplication [1, 2, 3, 1, 2, 3]
Numpy array multiplication [2 4 6]


In [ ]:

start = time.time()
py_list = [i*2 for i in range(1000000)] 
print("\n List operation time: ", time.time() - start)

#numpy for faster operations
start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.08968520164489746

 Numpy operation time:  0.004698514938354492


In [18]:
#creating array from scratch
zeros = np.zeros((3,4))
print("\n Zeros \n", zeros)

ones = np.ones((2,3))
print("\n ones \n", ones)

full = np.full((2, 2), 7)
print("\n full \n", full)

random = np.random.random((2, 3))
print("\n random \n", random)

seq = np.arange(0, 10, 2)
print("\n sequence \n", seq)


 Zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones 
 [[1. 1. 1.]
 [1. 1. 1.]]

 full 
 [[7 7]
 [7 7]]

 random 
 [[0.3033053  0.80559765 0.35504502]
 [0.06142711 0.7264928  0.90763782]]

 sequence 
 [0 2 4 6 8]


In [21]:
#vector, matrix, tensor

vector = np.array([1, 2, 3])
print ("\n Vector : ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\n Matrix :\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("\n Tensor : \n", tensor)


 Vector :  [1 2 3]

 Matrix :
 [[1 2 3]
 [4 5 6]]

 Tensor : 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
# array properties
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\n Shape of array :", arr.shape)
print("\n Dimension of array :", arr.ndim)
print("\n Size of array :", arr.size)
print("\n Data type of array :", arr.dtype)



 Shape of array : (2, 3)

 Dimension of array : 2

 Size of array : 6

 Data type of array : int64


In [ ]:
#Array reshapping